version: "3.4"

services:
  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail https://localhost/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    shm_size: 256mb
    environment:
      - WEB_APP__DOMAIN=localhost
      - ASPNETCORE_ENVIRONMENT=Production
      - HTTP_PORT=80
      - HTTPS_PORT=443
      - ASPNETCORE_URLS=http://0.0.0.0:80;https://0.0.0.0:443
    volumes:
      - ./.temp-keys:/root/.aspnet/DataProtection-Keys
      - ./.aspnet/https:/https/:ro
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - api
    tty: true
    ports:
      - "80:80"
      - "443:443"
    shm_size: 256mb
    volumes:
      - ./.logs:/var/log/nginx
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./nginx/ssl/:/etc/nginx/ssl/:ro
      - ./dist/:/dist/:ro
    restart: unless-stopped

  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - "1232:80"
      - "5341:5341"
    shm_size: 128mb
    environment:
      - ACCEPT_EULA=Y
# echo 'p@ssw0rd' | docker run --rm -i datalust/seq config hash
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=
    volumes:
      - ./.logs/seq/:/data
    restart: unless-stopped